void runCommand(char*);
void parseCommand(char**, char*);
int getTillChar(char*, char*, char);
int stringEqual(char*, char*);
void typeCommand(char*);
void executeCommand(char*);
void dirCommand();
void copyCommand(char*, char*);
void print(char*);
void printNum(int);
int mod(int, int);
